#!/bin/sh
# $Id: Distro,v 1.3 2005/01/13 12:16:08 jettero Exp $

./distclean
check_manifest || exit 1
perl Makefile.PL && make dist

mkdir -p dist

    n=`ls Math*gz`;
    date=`date`;
    cat PhysicalValue.pm | pod2html > ./dist/PhysicalValue.html
    rm -vf pod* ./dist/Math*gz
    mv -v Math*gz ./dist

cat > ./dist/PhysicalValue.b.html << EOF
<p>
Math::Units did <em>almost</em> what I wanted.  I really wanted something like Math::Calc::Units -- which felt unfinished, and
hadn't been updated for years.  This (<a href="$n">$n</a>) is something I wrote for dividing things like "6,500 ft" and "43 s" and
getting "103.16 miles/hour".  This module uses Math::Units and Math::Algebra::Symbols to do all it's magic.  Really, PhysicalValue
is just a collection of clever operator overloads.
Check out the man page: <a href="?eo_cat=PhysicalValue.html">Math::Units::PhysicalValue module</a>.
Last updated on $date
EOF

ssh mei.net "(cd /home/voltar/html/PerlModules/; rm *PhysicalValue*)"
(cd dist; chmod 644 *.html *.gz)
scp -p dist/* mei.net:/home/voltar/html/PerlModules/

rm -rvf dist
